services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votedb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  app:
    build: ./backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/votedb
      PORT: 3000
      TRUST_PROXY: "true"
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: ["node", "dist/index.js"]

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - app

volumes:
  db_data:
